In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
np.__version__

'1.16.0'

### 1 创建长度为10 的一维全为0 的numpy数组，然后让第五个数字为1

In [5]:
s1 = np.zeros(shape=10)
s1[4] = 1
s1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 2 创建元素为10到49的ndarray的对象

In [12]:
np.random.randint(10,50,size = 10)#返回【10，50）之间的随机整数 个数=10

array([21, 19, 41, 12, 45, 42, 40, 15, 37, 38])

In [9]:
np.linspace(10,49,10)

array([10.        , 14.33333333, 18.66666667, 23.        , 27.33333333,
       31.66666667, 36.        , 40.33333333, 44.66666667, 49.        ])

In [13]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3 将第二题的元素位置反转

In [15]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 4 使用np.random.random 创建一个10*10 的ndarray对象，并打印最大最小元素

In [17]:
a4 = np.random.random(size=(10,10))#返回随机的浮点数，在半开区间 [0.0, 1.0) 大小10*10
a4

array([[0.69354859, 0.41628266, 0.27350107, 0.42968292, 0.8791434 ,
        0.588092  , 0.1596765 , 0.48955312, 0.16984825, 0.49222653],
       [0.62320976, 0.50156529, 0.61941528, 0.91642033, 0.02717735,
        0.76194063, 0.66366849, 0.82139724, 0.58352667, 0.91083036],
       [0.13555328, 0.33988328, 0.15999565, 0.0054019 , 0.76253418,
        0.10549581, 0.80018897, 0.53402655, 0.02529389, 0.62419541],
       [0.04305328, 0.10480196, 0.04278956, 0.30139861, 0.74017748,
        0.69793187, 0.34565088, 0.83093283, 0.13614695, 0.07559973],
       [0.4992359 , 0.65038931, 0.31396996, 0.59597857, 0.47505849,
        0.84967951, 0.95497722, 0.95870263, 0.06318811, 0.19418686],
       [0.66802803, 0.94372829, 0.34752645, 0.63355621, 0.02800499,
        0.32247998, 0.18539843, 0.72895035, 0.15752736, 0.17803431],
       [0.81733858, 0.14557035, 0.47775327, 0.51974778, 0.25844346,
        0.69046709, 0.96977442, 0.11459192, 0.84847326, 0.82537038],
       [0.02350013, 0.71117379, 0.2430804

In [19]:
a_min,a_max = a4.min(),a4.max()
a_min,a_max

(0.005401899784440056, 0.9697744162366995)

### 5 创建10*10 的ndarray 对象，且矩阵边界全为1 ，里边全为0

In [23]:
a5 = np.zeros(shape=(10,10))
a5[[0,9]] = 1 #第0，9行 赋值为1
a5[:,[0,9]] = 1#0,9列 赋值为1
a5


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
b5 = np.ones(shape = (10,10))
b5[1:-1,1:-1] = 0
b5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 6 创建一个每一行都是0到4的5*5矩阵

In [26]:
a6 = np.arange(0,25).reshape(5,5)
a6

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
a6 = [i for i in range(0,5)]
nd = np.array(a6*5)
nd.reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### 7 创建一个范围在（0，1）之间的饿长度为12 的等差数列

In [38]:
np.linspace(0,1,12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

### 8 创建一个长度为10的随机数组并排序

In [40]:
a8 = np.random.random(10)
a8

array([0.33778424, 0.25042357, 0.85002888, 0.25455714, 0.96824231,
       0.14098644, 0.86399778, 0.12040842, 0.65795179, 0.41064229])

In [43]:
a8.sort()
a8

array([0.12040842, 0.14098644, 0.25042357, 0.25455714, 0.33778424,
       0.41064229, 0.65795179, 0.85002888, 0.86399778, 0.96824231])

### 9 创建一个长度为10 的随机数组并将最大值替换为0

In [47]:
a9 = np.random.randint(0,10,size=10)
display(a9)
index_max =a9.argmax()

array([4, 8, 8, 8, 1, 1, 3, 9, 0, 0])

In [48]:
all_index_max =np.argwhere(a9==a9[index_max]).reshape(-1)
all_index_max

array([7])

In [50]:
a9[all_index_max] = 0
a9

array([4, 8, 8, 8, 1, 1, 3, 0, 0, 0])

### 10 如何根据第三列来对一个5*5矩阵排序

In [51]:
a10 = np.random.randint(0,100,size=(5,5))
a10

array([[14,  7, 25, 25, 37],
       [62, 25, 98, 97, 11],
       [54, 11, 52, 74, 97],
       [75, 16,  1, 78, 81],
       [22, 12, 71, 43, 74]])

In [54]:
a10[:,2]

array([25, 98, 52,  1, 71])

In [55]:
np.argsort(a10[:,2])#按列的数值从小到大排序，返回其对应的列号

array([3, 0, 2, 4, 1])

In [56]:
a10[np.argsort(a10[:,2])]

array([[75, 16,  1, 78, 81],
       [14,  7, 25, 25, 37],
       [54, 11, 52, 74, 97],
       [22, 12, 71, 43, 74],
       [62, 25, 98, 97, 11]])

### 11 给定一个4维矩阵 得到最后两维的和

In [58]:
a11 =np.random.randint(0,100,size=(2,3,3,3))
a11

array([[[[41,  5, 31],
         [62, 13, 67],
         [ 6, 12, 85]],

        [[72,  7, 32],
         [52, 80, 88],
         [66, 25, 57]],

        [[ 7, 82, 56],
         [55,  3,  2],
         [81, 48, 81]]],


       [[[69, 97,  0],
         [88, 30, 47],
         [61,  1, 21]],

        [[37, 84, 84],
         [45, 83, 67],
         [45, 21, 23]],

        [[95, 89, 34],
         [32, 78, 58],
         [43, 59, 77]]]])

In [59]:
a11.sum(axis=(2,3))

array([[322, 479, 415],
       [414, 489, 565]])

In [60]:
a11.sum(axis=(-1,-2))

array([[322, 479, 415],
       [414, 489, 565]])